const REQUIRED_VARS: string[] = [
  "ALLOWED_IP_ADDRESS",
  "ALLOWED_IP_ADDRESS_LOCAL",
  "DB_DATABASE",
  "DB_HOST",
  "DB_PASSWORD",
  "DB_PORT",
  "DB_USER",
  "JWT_SECRET",
  "PORT",
];

export default REQUIRED_VARS;
